### ISSUE TITLE
Move screen resolution to episode settings 

### ISSUE THREAD

**Issue by Shadowblitz16** [TheXTech/TheXTech#727] opened 2024-02-18 23:05 UTC
**Describe the issue**
Currently with the dynamic screen resolution it's impossible to build a level in which enemies trigger at a certain time.

This makes designing good levels really difficult.

**Example Case**

I am using hd resolution, and this screen shot for example...
![image](https://github.com/Wohlstand/TheXTech/assets/2453707/36a35fab-36b5-4024-bab6-2672b6882cfc)

By the time I each the goomba on the top platforms he already is done dropping through the gap in the platform and getting ready to walk off into the water.

If this level used gba resolution the goomba wouldn't even load.

**Additional context**
I think levels should be designed around screen sizes rather then level designers being at the mercy of what resolution the users use.

I do like the hd resolution I was using it for the invasion episode, but the only case where resolution makes a difference 
is if the episode dev spams enemies all over the place to achieve a higher level difficulty and to be honest that's 
bad level design and shouldn't be encouraged.

**Comment by ds-sloth** [comment] 2024-02-18 23:19
Mostly a duplicate of #710, feel free to share more thoughts there. We're aware of this issue and planning several tools to help content creators manage this complexity:

1. We are currently developing a `compat.ini` option that allows an episode to require NPC logic to always follow the default resolution, and caps the resolution at the default, and this will be included in our Config Update.

2. We also have an `npc.txt` option, `usedefaultcam = 1`, that has the same effect for a single NPC type.

3. Thirdly, we are considering a `compat.ini` option that allows an episode to indicate what its default resolution should be.

> I think levels should be designed around screen sizes rather then level designers being at the mercy of what resolution the users use.

This should be possible if we add the `compat.ini` option for setting a default resolution.

However, let me mention that TheXTech's multires system has always been designed to make episodes enjoyable to play at multiple resolutions. SMBX2 has a philosophy more like what you are describing here.

You had fun with The Invasion 2 in HD, and we've also fully playtested many of the most advanced and well-received SMBX 1.3 / LunaDLL episodes such as Analogue Funk and Yoshi's Archipelago. This would seem to counter your claim that multires makes designing good levels difficult. In general, the level designer should expect their content to be played in multiple resolutions, and make sure it plays well in each case.

**Closed by ds-sloth** 2024-02-18 23:19 UTC
Labels: duplicate, multires
