### ISSUE TITLE
[Bug] Forced State can clone powerups when switching characters

### ISSUE THREAD

**Issue by Superbloxen** [TheXTech/TheXTech#828] opened 2024-09-06 19:10 UTC
### Describe the issue

Example using 2 nondescript characters:

When in a hub world/level, collecting a powerup as Character A and pausing during the transition animation (on a frame Character A's state is changed) then switching characters will cause Character B to still be in the transition and also gain the powerup, effectively duplicating them across characters.

(Sorry if this is confusing, it's difficult to describe how to reproduce this bug)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#49987b0

### Platform

Android

### Processor architecture

None

**Comment by ds-sloth** [comment] 2024-10-22 14:29
This should be fixed now. Can you please let me know if the issue is still present in a new development build?

**Closed** 2024-12-21 17:55 UTC
Labels: native bug
