### ISSUE TITLE
Kamakaze fish

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#826] opened 2024-09-06 00:54 UTC
### Describe the issue

While swimming underwater and touch a fishes head the fish will die and the player will die aswell.
![2024-09-05_20-46-35 669_top](https://github.com/user-attachments/assets/90a2df40-28c2-4f5a-9dfa-02c9345ea6c1)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3..7-dev

### Version Hash

#590838a

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment] 2024-09-06 01:08
Duplicate of vanilla bug #435

**Closed by ds-sloth** 2024-09-06 01:08 UTC
Labels: duplicate
