### ISSUE TITLE
Level/Episode Asset System

### ISSUE THREAD

**Issue by P-Star7** [TheXTech/TheXTech#372] opened 2022-08-07 02:52 UTC
A proposal of an assets system, split into two parts: the assets themselves and how an episode or level automatically knows to load them.

There are already five extant asset packs for SMBX that are compatible with TheXTech:
SMBX64
Super Talking Time Bros. Series
A Super Mario Bros. X Thing
A Super Mario Bros. X Thing 2 Episode 1: Prelude to the Stupid
TheXTech
There are also two possible potential future asset packs already being developed - Nostalgic Paradise and my non-copyrighted asset pack.
Super Mario Bros. X Redrawn is also a potential asset pack that we can convert to this format due to already having all graphics replaced. (except maybe hardcoded, but I can redraw that easily)

So how are we supposed to play episodes that use different asset packs without having multiple installations of TheXTech? And what if someone wants to make a single level using the theme of an asset pack without having to put all those graphics and musics to their level's folder just for a single level?

My proposed solution is to replace the "graphics", "music", and "sounds" folders with one "assets" folder. Subfolders inside the assets folder will have unique names and contain these three types of assets. This also makes it possible to use the .txt files that ASMBXT and ASMBXT2E1 need without affecting other levels. It will also make it possible for me to include .txt hotfixes in the TheXTech asset folder (npcblocktop=0 SMB3 1up, inedible 3up moon, Mouser, and Potion Door, nofireball=0 Nipper) without interfering with the SetupVars for NPCs when playing SMBX64 levels.

2. Loading Assets
A .lvlx file and .wldx file will have a parser for the name of the asset pack to use. If the asset pack is not found, a notice is given and the user is returned to the episode selection menu. All .lvlx files inside an episode folder or deeper will "inherit" the asset pack to use from the .wld file, only using a different asset pack if their individual .lvlx says to use a different asset pack. (Giving levels an "asset" value is meant to work with playing levels standalone from the command line or hopefully in the future, from the title screen.)

Note: All ".lvl" files will automatically load SMBX64 due to the lack of an assets field in them, and due to being created in SMBX 1.3 or lesser.

Work that will be needed to prepare asset pack compatibility (I volunteer to do it)
-Conversion of STTB1, STTB2, STTB2: The Last Levels, ASMBXT, and ASMBXT2E1 to .wldx and adding asset field. Unfortunately, this means that Wohlstand must rehost the episodes and asset packs.
-Preparing the asset folders for these three assets (SMBX64 is already prepared by Wohlstand)
-Adding the ASMBXT, ASMBXT2, and TheXTech .txt codes to the npc graphics folder for each asset

**Comment by LoveBodhi** [comment] 2022-08-07 02:55
My NFTWL and FTW are unlisted (they're stalled right now)

**Comment by ChristianSilvermoon** [comment] 2022-08-07 05:27
Possibly a Duplicate of #291

**Comment by 0lhi** [comment] 2022-08-07 15:14
> Possibly a Duplicate of #291

Yeah, this is a duplicate. [Another one](https://github.com/Wohlstand/TheXTech/issues/348) at that.

@P-Star7 If you have additional suggestions for asset systems, bring them up at #291. Do not make a third duplicate.

**Closed** 2022-08-07 15:14 UTC
Labels: duplicate
