### ISSUE TITLE
Wii U (Wuhb format) - Map selection issue

### ISSUE THREAD

**Issue by LopezTutoriales** [TheXTech/TheXTech#770] opened 2024-06-24 18:18 UTC
### Describe the issue

Hi! in the map selection menu, it does not display the map correctly, it does not matter what resolution I use, it always does the same thing. This is a screenshoot:
![20240624_174923](https://github.com/TheXTech/TheXTech/assets/5817696/ad322826-73ee-4a4c-ae24-68cb924e6e12)
Thank you very much! ✌🏻😁

### A type of bug

Compatibility bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Platform

Wii U

### Processor architecture

Not specified / I don't know

**Comment by Wohlstand** [comment] 2024-06-24 18:40
Hello!
Looks weird... Does this glitch happens on the world map only? Lemme try this out on my end...

**Comment by LopezTutoriales** [comment] 2024-06-24 18:50
Yeah! It always happens on the world map. It's very weird. Thank you very much

**Comment by Wohlstand** [comment] 2024-06-24 18:51
By the way, what the kind of Wii U you have? Mine is Japanese with the 5.5.5 firmware version. I hacked it with Tiramisu and the latest Aroma is installed here.

**Comment by Wohlstand** [comment] 2024-06-24 18:52
Oh, the thing I tested on my end was Tiramusi, I should try the work via Aroma, because last time it had a bug that prevents loading the game after the first launch, and that had been fixed by recent Aroma update.

**Comment by Wohlstand** [comment] 2024-06-24 19:02
I trying the devel thing now via Aroma to see what happen. The stable version should work fine. But just in a case, please try it too... I going to do the same on my end. I tried the "Analogue Funk" game, and it worked just fine, no world map glitches, trying the SMBX game to see how it works...

**Comment by Wohlstand** [comment] 2024-06-24 19:06
Actually, I got it reproduced too:

![20240624_220601.jpg](https://github.com/TheXTech/TheXTech/assets/6751442/1e4bfe0f-16b6-4ad4-ac8b-f155374cc0c7)

This happen with the SMBX installed by legacy way (single assets way).

**Comment by Wohlstand** [comment] 2024-06-24 19:36
Now, trying the stable version to see what happen...

**Comment by Wohlstand** [comment] 2024-06-24 19:53
Stable version just works (rpx via Aroma):

![20240624_225242.jpg](https://github.com/TheXTech/TheXTech/assets/6751442/2eb24c8e-0dc8-4a89-81c8-404f14badc27)

![20240624_225257.jpg](https://github.com/TheXTech/TheXTech/assets/6751442/48d0e422-eefe-4ca7-8f43-e2bd5aaf4f32)

**Comment by ds-sloth** [comment] 2024-06-24 20:01
So, there's some rendering bug that affects Aroma but not Tiramisu, and appears only in the dev branch? Can you bisect before and after the multires and config merges?

**Comment by LopezTutoriales** [comment] 2024-06-24 20:23
> By the way, what the kind of Wii U you have? Mine is Japanese with the 5.5.5 firmware version. I hacked it with Tiramisu and the latest Aroma is installed here.

My Wii U is European with the 5.5.5 firmware version and I have Tiramisu and Aroma in latest version

**Comment by LopezTutoriales** [comment] 2024-06-24 20:26
> Oh, the thing I tested on my end was Tiramusu, I should try the work via Aroma, because last time it had a bug that prevents loading the game after the first launch, and that had been fixed by recent Aroma update.

Another error that the wuhb version has is that when you click "exit" the console freezes with a black screen

**Comment by LopezTutoriales** [comment] 2024-06-24 20:35
> Thanks a lot for the report!
> 
> Some additional questions:
> 
> * Does the stable 1.3.6.5 build work as expected?
> * Does the world map work as expected when playing on the TV instead of the gamepad?


Thanks you for answering!

* The stable version 1.3.6.5 works perfectly (rpx via Aroma)
* Failure on both, both TV and Gamepad

**Comment by Wohlstand** [comment] 2024-06-24 21:18
> Another error that the wuhb and rpx versions have is that when you click "exit" the console freezes with a black screen

That's a known issue happen with Aroma only (to solve it I should implement the missing code that pokes loading of the Wii U main menu after quitting the game). You can easily power off console by GamePad's power button and boot it again. It doesn't freeze, but it quits into nothing.

**Comment by Wohlstand** [comment] 2024-06-24 21:23
> Can you bisect before and after the multires and config merges?

Yea, uno momento...

**Comment by Wohlstand** [comment] 2024-06-24 23:11
![20240625_021026.jpg](https://github.com/TheXTech/TheXTech/assets/6751442/4e6a46e1-0a49-481f-a857-dd362290cd4d)

**Comment by Wohlstand** [comment] 2024-06-24 23:12
Huh, this bug gets reproduced on CEMU too :eyes:
![изображение](https://github.com/TheXTech/TheXTech/assets/6751442/f9c65571-9b22-41e6-a648-45206b9d90e5)

**Comment by LopezTutoriales** [comment] 2024-06-25 01:08
> Huh, this bug gets reproduced on CEMU too 👀 ![изображение](https://private-user-images.githubusercontent.com/6751442/342518286-f9c65571-9b22-41e6-a648-45206b9d90e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNzczNTgsIm5iZiI6MTcxOTI3NzA1OCwicGF0aCI6Ii82NzUxNDQyLzM0MjUxODI4Ni1mOWM2NTU3MS05YjIyLTQxZTYtYTY0OC00NTIwNmI5ZDkwZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMDA1NzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjcyZGE0Mjc0NDA2ZDVkN2Q1Y2JjMDMwZTFlNjMxMDg5NWNiNTc4NjQ3ZmEzYjQwNmUwZGI0MzE3NDE3ZWJlZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QllH8meFJRAeeX-6QjG-V6-0uYIo8qL_YrHJOfJvq6o)

This bug is very rare. Could it be due to the wuhb format or the rendering?

**Comment by Wohlstand** [comment] 2024-06-25 01:20
This happens even with RPX (CEMU can't run WUHB yet, so, RPX is ran here)

**Comment by Wohlstand** [comment] 2024-06-25 01:43
About the black screen bug, I fixed it just now.

**Comment by LopezTutoriales** [comment] 2024-06-25 07:00
> About the black screen bug, I fixed it just now.

Perfect! Thank you so much for your work! ✌🏻😁👍🏻

**Comment by ds-sloth** [comment] 2024-07-05 19:31
@LopezTutoriales thanks very much for the report. Once the new development build (hash `8307506f`) is ready, can you please confirm whether this issue is fixed? I have fixed it in Cemu but don't have a Wii U to test on.

**Comment by Wohlstand** [comment] 2024-07-06 04:31
Okay, for  now there is new build #5da71ea2 that uses a fixed SDL2 instead of initial workarounds done that also fixing other bugs related to tall/thin sections rendered with glitches.

![20240706_065510.jpg](https://github.com/TheXTech/TheXTech/assets/6751442/1630f367-98ab-47dd-8520-749ab462b8cb)

![20240706_065156.jpg](https://github.com/TheXTech/TheXTech/assets/6751442/fbcb15e0-2e2a-4d63-b88b-1771af71b344)

![20240706_065225.jpg](https://github.com/TheXTech/TheXTech/assets/6751442/d00c15d0-8e20-4f12-b1c7-bd6ca8778015)

![20240706_065243.jpg](https://github.com/TheXTech/TheXTech/assets/6751442/3662279f-f513-43c1-b170-fcc29b65b79b)

**Comment by LopezTutoriales** [comment] 2024-08-04 10:39
I just tested the commit (hash 8307506f) and it works perfectly, but however, I have also tested the current commit (hash 70c116b) and the same error that I mentioned at the beginning continues.

![20240804_123017](https://github.com/user-attachments/assets/3e4d3d3d-4af4-41e8-8af6-1c5e3007883f)

**Comment by Wohlstand** [comment] 2024-08-04 10:52
> but however, I have also tested the current commit (hash [70c116b](https://github.com/TheXTech/TheXTech/commit/70c116bb58a5efee667de91ab6aebb307d88f005)) and the same error that I mentioned at the beginning continues.

Cany you remember, which error (if not the same render error)?

**Comment by LopezTutoriales** [comment] 2024-08-04 11:14
Thanks for your reply, the error that continues is the one in this message:

> ### Describa el problema
> Hola! en el menú de selección de mapas no me muestra el mapa correctamente no importa la resolución que use siempre hace lo mismo. Esto es un pantallazo: Muchas gracias! ✌🏻😁 ![20240624_174923](https://private-user-images.githubusercontent.com/5817696/342448205-ad322826-73ee-4a4c-ae24-68cb924e6e12.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NzAyMjQsIm5iZiI6MTcyMjc2OTkyNCwicGF0aCI6Ii81ODE3Njk2LzM0MjQ0ODIwNS1hZDMyMjgyNi03M2VlLTRhNGMtYWUyNC02OGNiOTI0ZTZlMTIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDRUMTExMjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjA2YTBiZTBjNDc1NTgzNDUyZmE5MmIwYzVmODVlNDc0YzljM2RhZTk0MTExN2JiN2Q1MWFkNWI3MmZlYWE1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qM31s2m7yVF9Bwqb_hin2-eKDlUSEjNEk6bN9kFhNNo)
> 
> ### Un tipo de error
> Error de compatibilidad
> 
> ### ¿Este problema ocurre siempre o aleatoriamente?
> Siempre pasa
> 
> ### Versión
> 1.3.7-dev
> 
> ### Versión Hash
> _Ninguna respuesta_
> 
> ### Plataforma
> Wii U
> 
> ### Arquitectura del procesador
> No especificado / No lo sé
> 
> ### Archivo de registro (si está presente)
> _Ninguna respuesta_
> 
> ### Caso de ejemplo
> _Ninguna respuesta_
> 
> ### Grabación
> _Ninguna respuesta_
> 
> ### Grabación de vainilla
> _Ninguna respuesta_
> 
> ### Contexto adicional
> _Ninguna respuesta_

**Comment by Wohlstand** [comment] 2024-08-04 11:17
Sounds like the custom SDL2 build was lost during some works by @ds-sloth or didn't linked properly :thinking:
I'll try to check some soon, for now I have a headache for no reason...

**Comment by LopezTutoriales** [comment] 2024-08-04 11:21
Don't worry @Wohlstand, thanks for your reply and I hope you recover soon 😁

**Comment by ds-sloth** [comment] 2024-08-13 15:20
I believe this has been fixed now. The issue was that devkitPro started including their own SDL2 build in their CI docker images, and our builds were incorrect using their build.

@LopezTutoriales, can you please confirm that the issue is fixed? Thank you!

**Comment by Wohlstand** [comment] 2024-12-17 08:31
@LopezTutoriales, did you tested the thing on your end? I'll close this because of no responce for so long time.

**Closed by Wohlstand** 2024-12-17 08:31 UTC
Labels: native bug, NEED A TEST
