### ISSUE TITLE
Pipe returns do not work out of section bounds

### ISSUE THREAD

**Issue by Shadowblitz16** [TheXTech/TheXTech#726] opened 2024-02-18 21:15 UTC
Entering the pipe works but when I try to return from the area, the first section is not reloaded

My Os Info is:
```
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 6.5.0-17-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 15.0 GiB of RAM
Graphics Processor: RENOIR
```

![image](https://github.com/Wohlstand/TheXTech/assets/2453707/7cd5ccb7-0b0a-4ac2-a1cf-412f9d6bf776)
![image](https://github.com/Wohlstand/TheXTech/assets/2453707/35376018-f197-4d9e-931e-b559465ea878)

This is what it looks like after I enter the pipe again to return from the bonus section...
![image](https://github.com/Wohlstand/TheXTech/assets/2453707/47c5e459-b433-4bab-aee1-f43636148b61)

**Comment by Wohlstand** [comment] 2024-02-19 13:08
This is a pure vanilla bug, here is a recording done by the [SMBX-R](https://github.com/Wohlstand/smbx-experiments):

![Scr_2024-02-19_16-06-05](https://github.com/TheXTech/TheXTech/assets/6751442/9a092f43-d59c-47a7-8d26-64e7c4f546f5)

The recording by TheXTech:
![Scr_2024-02-19_16-04-07](https://github.com/TheXTech/TheXTech/assets/6751442/329ebfc7-3bd0-47fd-93a9-ff4bb9c43884)

Demo level:
[Pipes death.lvl.zip](https://github.com/TheXTech/TheXTech/files/14331466/Pipes.death.lvl.zip)

**Comment by ds-sloth** [comment] 2024-02-19 18:27
I'm confused that you self-assigned this.

At first I didn't understand the issue, but now that you've made an example, I don't think we need to fix this case (even though it would be easy to do so). It's immediately obvious to a creator that this level design doesn't work in SMBX 1.3, so there won't be any SMBX 1.3 content that uses it. And I don't think this an an especially important level design pattern, even if it is interesting.

Of course, it will be good to ensure that Moondust has a better section calculation heuristic than TheXTech / SMBX 1.3, but an issue should be filed there to verify the section logic, not here.

**Comment by Wohlstand** [comment] 2024-02-19 18:31
> At first I didn't understand the issue, but now that you've made an example, I don't think we need to fix this case (even though it would be easy to do so). It's immediately obvious to a creator that this level design doesn't work in SMBX 1.3, so there won't be any SMBX 1.3 content that uses it. And I don't think this an an especially important level design pattern, even if it is interesting.

I know actually one level at [THIS](https://smbxarchive.wohlsoft.ru/SMBX%201.3/Miscellaneous%20Level%20Contest%20Entries%20-%20The%20Crazy%20Cat-Corridor%20-%20fixed.7z) episode that did that, and that fails - leads a death of player.

**Comment by ds-sloth** [comment] 2024-02-19 18:33
> Actually, at the entrance, that failure had been noted in message boxes. That episode is a result of a contest, and the hub tells judgement result and points to procs and cons of the done level.

A good note, and a further reason we don't need to fix this. It's clear that the community already understood the situation (even if the contest submitter did not).

**Comment by Wohlstand** [comment] 2024-02-19 18:36
That intro:
![Scr_2024-02-19_21-35-13](https://github.com/TheXTech/TheXTech/assets/6751442/43987eac-a0cf-43d1-86a3-1562403137dd)

**Comment by Wohlstand** [comment] 2024-02-19 18:45
P.S. I tested out that my demo on X2, and it also reproduces this bug.

Moondust Engine is only thing where it doesn't fails: just, because I assign the NEAREST section to the warp exit, even it doesn't intersects it.

![Scr_2024-02-19_21-43-48](https://github.com/TheXTech/TheXTech/assets/6751442/7d0f1cf3-1728-4b71-ba7a-10129cdecc8a)

**Comment by Wohlstand** [comment] 2024-02-19 18:46
Actually, my tip is making such secret pipes hidden under screen never exit directly, let player exit through another pipe that will be visible. Or at least appear from underground.

**Comment by ds-sloth** [comment] 2024-02-19 18:58
Thanks for bringing this case to our attention; it's always good for us to document the vanilla behavior of the SMBX engine. Moondust works for your level design, but TheXTech (like SMBX 1.3 and SMBX2) will keep the old behavior. Wohlstand provided some useful tips for you to make your design work in TheXTech.

**Closed by ds-sloth** 2024-02-19 18:58 UTC
Labels: help wanted, vanilla bug
