### ISSUE TITLE
Lowsers Conquest Beta corrupted textuers

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#814] opened 2024-09-02 02:21 UTC
### Describe the issue

All levels have the wrong textures.

![2024-09-01_18-56-15 511_top](https://github.com/user-attachments/assets/d7066df7-d762-47cf-b23b-efe8023122c2)
![2024-09-01_18-56-24 950_top](https://github.com/user-attachments/assets/07f69a6e-ce18-42b7-be39-6162a69996c1)
![2024-09-01_18-57-21 646_top](https://github.com/user-attachments/assets/8f060045-3d91-4d0a-bd9d-14f31d4bcc99)
![2024-09-01_18-58-03 949_top](https://github.com/user-attachments/assets/43e418ed-1274-40ce-89f3-79bba865f8ed)
![2024-09-01_18-58-34 884_top](https://github.com/user-attachments/assets/19594272-b56d-489c-8196-197f3864a71d)
![2024-09-01_18-58-44 016_top](https://github.com/user-attachments/assets/39756d19-7181-448f-bbdc-b4fd55f54503)
![2024-09-01_18-59-51 966_top](https://github.com/user-attachments/assets/e28ff90a-05b0-4dc8-a08b-0cb7ea943d54)
![2024-09-01_19-00-14 899_top](https://github.com/user-attachments/assets/75cdeafa-7a20-469a-aa14-63b856bccdfb)
![2024-09-01_19-41-32 138_top](https://github.com/user-attachments/assets/9c3c4557-be76-441d-a8d1-5772480992d1)
![2024-09-01_19-40-32 616_top](https://github.com/user-attachments/assets/0f151a99-d741-4bfc-aa31-a06482b0435a)

### A type of bug

Compatibility bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#8a135c5

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

### Log file (if presented)

[TheXTech_log_2024_09_01_22_07_21.txt](https://github.com/user-attachments/files/16831552/TheXTech_log_2024_09_01_22_07_21.txt)

**Comment by ds-sloth** [comment] 2024-09-02 12:35
Let me take a look at the converted asset packs I sent you -- they're from March of this year and it's possible they were made with an outdated version of the conversion scripts. Or it's possible that there is still some bug in the conversion scripts.

**Comment by ds-sloth** [comment] 2024-09-02 15:17
I've confirmed that there is an issue here even with the latest scripts. It isn't as severe as what you found here, but there are still textures that are converted as the wrong size. I will look more closely later.

**Comment by Trickiy** [comment] 2024-09-03 20:00
After testing build [8267f3c](https://github.com/TheXTech/TheXTech/commit/8267f3c447bbd0b64783b8736c33f039d5c30af6) the holes in the tiles are fixed but some blocks are misaligned.
![2024-09-03_15-43-15 280_top](https://github.com/user-attachments/assets/8c31d117-a335-4d04-bf21-9ea852db36ec)
![2024-09-02_19-50-01 860_top](https://github.com/user-attachments/assets/671c49fb-c769-4b4e-9263-31b05accc4fe)

**Comment by ds-sloth** [comment] 2024-09-03 20:48
I see, so Lowser's Conquest did use hacked blocks. Great to know that that fixes this.

For the alignment: I can't reproduce this on PC or 3DS. Which levels are affected?

**Comment by Trickiy** [comment] 2024-09-03 21:06
The level in the images is Special: Hedgehoppinging Zone and I found a bgo that is floating in the level Dropstone Cavern it's under the ? block.
![2024-09-03_16-49-04 473_top](https://github.com/user-attachments/assets/af9d679d-7e20-4689-afb4-c24d2eef91d8)

**Comment by ds-sloth** [comment] 2024-09-03 21:17
Both of those are how the episode has always been, no bugs there. So I think the main problem here was the hacked blocks fixed by [8267f3c](https://github.com/TheXTech/TheXTech/commit/8267f3c447bbd0b64783b8736c33f039d5c30af6). 

We can close this issue for now; please open a new one if you notice any other issues.

**Closed by ds-sloth** 2024-09-03 21:17 UTC
Labels: asset customization, non-desktop
