### ISSUE TITLE
In-Game Hints

### ISSUE THREAD

**Issue by 0lhi** [TheXTech/TheXTech#690] opened 2024-01-17 21:10 UTC
To communicate SMBX peculiarities to the user and to inform about updates in Modern Mode, In-Game Hints that appear during the loading screen and/or the pause menu will be helpful.

![Hints](https://github.com/Wohlstand/TheXTech/assets/74732674/afe14b4e-7c80-47c4-81dd-cdc26babd033)

**Comment by Superbloxen** [comment] 2024-01-22 22:56
> ![Hints](https://private-user-images.githubusercontent.com/74732674/297517928-afe14b4e-7c80-47c4-81dd-cdc26babd033.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NjM4MDQsIm5iZiI6MTcwNTk2MzUwNCwicGF0aCI6Ii83NDczMjY3NC8yOTc1MTc5MjgtYWZlMTRiNGUtN2M4MC00N2M0LTgxZGQtY2RjMjZiYWJkMDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDIyNDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NzI4ZmE2MDQzOGZmYTM1ZDBmNDQ3NGY3YmNkNTcwMjdhNmM1ZDJkNGMyYzUyN2FkMmNmOTlhNDlmZTc1MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QyJeFmN86zlaQTfgzocktr-Ors4f1CYd1aIai7F0V_4)

This is a good idea, but I'm not a fan of the text appearing on the pause screen, as it feels more like an ad than a hint.  If it's possible, some text above saying "HINT" would make it better. 

Additionally, the text is in all caps, which makes it seem more aggressive and ad-like. Perhaps softening the text to look as it appears on the top of the screen would make it easier on the eyes.


And could this support custom hints or even objectives relevant to the stage? Perhaps it could be changed through Events or used to display how much of an item has been collected / destroyed such as Switch Goombas / Red Coins / Objects in a layer?

**Comment by ChristianSilvermoon** [comment] 2024-02-04 22:19
I like it appearing on the pause screen. It somewhat reminds me of the Copy Ability tutorials seen in Kirby Games, and can provide good and useful context-sensitive info to the player if they're confused.

**Comment by ChristianSilvermoon** [comment] 2024-05-03 20:46
> What, if anything, is still needed here?
> 
> We currently have hints for the purple pet mount (which sometimes spoil the presence of one in a level, so it may be better to only display this when the player is actively riding one?) and to indicate what will happen when the player fails with 0 lives left.

Ideas I can think of for additional hints
- How to ride Rainbow Shells if one has been on screen during the current level
- - A lot of players don't know you can shell surf.
- Breakable power-up related bricks
- - I didn't know these could be broken for many years

**Comment by ds-sloth** [comment] 2024-08-14 01:46
I previously added a hint for rainbow surfing, and now I just added the last three hints suggested by 0lhi.

I think that this feature is now complete and we should be able to close the issue after people have played with these hints for a bit. We can always add more hints in the future as needed.

**Comment by Superbloxen** [comment] 2024-08-14 02:49
I have one question before the issue is closed that's in a similar vein to the hint system: Would it also be possible to have an ingame version of the Gameplay Manual to communicate the individual mechanics of SMBX NPCS + player characters to people who are new to the game outside of levels/hints?

**Comment by Trickiy** [comment] 2024-08-14 05:48
This is similar to my idea to have info be displayed when the mouse/stylus hovers over a item, block, npc, settings, or anything else while in the editor.

**Comment by ds-sloth** [comment] 2024-08-14 11:24
Thanks for the suggestions!

An in-game copy of the manual is a great idea but it would actually be pretty difficult to implement. We have a pretty nice text system but it's not designed for displaying full documents. It's definitely *possible* but won't be easy to implement quickly. Feel free to open a new issue so we can track it. 

Tooltip editor hints also sound like a good idea to me. Please file another issue so we can track them. How many items (roughly) are you thinking would get these? This kind of thing is pretty memory-intensive but we could at least offer it on desktop.

**Comment by Trickiy** [comment] 2024-08-14 17:17
I would reasonably think of doing what is too vague or hard to understand for beginners like myself. having the mini info box simply say whether a block is solid or transparent, Wich would be the same for most so having one info box being shared between them all would work well. As of typing this I rember that there's the 3ds browser, it is possible to put documents on a site and animated sprites. This would be a fantastic solution because all that would be needed is to scan a qr code to find the site. Here's Wofyxons opensorced [site](https://github.com/Wolfyxon/3ds-web-stuff) as this would be a great solution.

**Closed** 2024-12-21 17:53 UTC
Labels: enhancement, UI, localization
