### ISSUE TITLE
scene-62 and scene-63 might be bugged

### ISSUE THREAD

**Issue by Shadowblitz16** [TheXTech/TheXTech#736] opened 2024-03-01 19:50 UTC
graphics might be bugged for scene 62 and 63
![image](https://github.com/TheXTech/TheXTech/assets/2453707/bafff42d-7c08-459d-881a-589cacbc2525)
![image](https://github.com/TheXTech/TheXTech/assets/2453707/a604d289-47a5-420b-82b0-a437ad39c2e9)

**Comment by Wohlstand** [comment] 2024-03-01 19:55
Both these scenes are animated originally, and they WILL bug in Moondust Editor if you don't provide the INI file (`scene-62.ini` and `scene-63.ini`) to tell that they aren't animated:
```ini
[scenery]
animated = 0
frames = 1
```

**Comment by Wohlstand** [comment] 2024-03-01 19:55
And also, they will bug in TheXTech too until the support of these INI files will be added sooner.

**Comment by ds-sloth** [comment] 2024-03-01 21:10
From the point of view of TheXTech, this is a duplicate of the world map portion of #427.

**Closed by ds-sloth** 2024-03-01 21:10 UTC
Labels: duplicate
