### ISSUE TITLE
[Vanilla BUG] NPC can block under the invisible block

### ISSUE THREAD

**Issue by LoveBodhi** [TheXTech/TheXTech#479] opened 2023-01-28 08:11 UTC
Invisible Block should only be able to hit by players instead of along with NPC's.

**Comment by 0lhi** [comment] 2023-01-28 10:03
Duplicate of #126

**Closed by 0lhi** 2023-01-28 10:03 UTC
Labels: duplicate

**Comment by LoveBodhi** [comment] 2023-01-28 11:03
Argh... I didn't saw related issue! No!
