### ISSUE TITLE
AoD player spawns slightly in the ground

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#791] opened 2024-08-16 20:15 UTC
### Describe the issue

When I create a level in Adventuer of Demo like this 
![image](https://github.com/user-attachments/assets/c66e5021-62d2-4b9f-8f86-47a38e048869)
with any block and play, it dosen't need to be played within the editor. The player will start zooming left and right backwards. Only happens in Adventures of Demo for some reason.

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#29ca69c

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment] 2024-08-16 22:43
I can't reproduce this on desktop. It's possible it's caused by the same underlying issue as #789. I'll investigate further now.

**Comment by Superbloxen** [comment] 2024-08-16 22:59
This happens on the desktop and android versions too, I have a feeling that it's because of the characters' altered heights with .ini files because the SMBX Asset Pack doesn't have the same issue despite being on the same version.

**Comment by ds-sloth** [comment] 2024-08-17 00:29
I didn't find this on the desktop version myself, can you explain how to reproduce it? A GIF recording of making the level would be great.

**Comment by ds-sloth** [comment] 2024-08-17 00:40
I can't reproduce this on 3DS. I'm eager to hear back from one of you about how to reproduce the issue.

**Comment by Trickiy** [comment] 2024-08-17 01:02
it's very simple to recreate maybe If you have the same settings:
![image](https://github.com/user-attachments/assets/cf072c3a-3dbd-4e82-80c0-8671a3e2a7bf)

![image](https://github.com/user-attachments/assets/533da6b3-1fee-4da5-bd81-2aa496485735)

![image](https://github.com/user-attachments/assets/c9869b63-ebd0-4a2c-97db-c8e316b12ac9)

![image](https://github.com/user-attachments/assets/2451a2fe-59db-4f81-a79d-bd62cdc9aada)

![image](https://github.com/user-attachments/assets/88b16d85-6ff2-46b1-9ec4-5a175d6af5ac)

then exit the game reopen goto AoD and recreate the level without moving the player start position.

**Comment by Trickiy** [comment] 2024-08-17 01:05
I am explaining how to reproduce this way because the gif recording is not usable yet on 3ds, and I don't have a computer. So I am handicapped in that regaurd too.

**Comment by ds-sloth** [comment] 2024-08-17 01:20
> recreate the level

Do you mean that you should open a level that you previously created in SMBX in AoD? That's not actually permitted -- levels are intended to be played in the same asset pack they were created using (and later versions of the game will try harder to enforce this).

I'm sorry for the confusion -- we should find a place to specify this until the game enforces it.

**Comment by Trickiy** [comment] 2024-08-17 01:28
No I ment to create a new level, sorry for my odd choice of words.

**Comment by Superbloxen** [comment] 2024-08-17 01:30
I first opened the editor and created a new level and placed tiles directly underneath P1/P2's spawn points then ran the level, causing the character to act as if they were in a wall and slide off the stage.

**Comment by ds-sloth** [comment] 2024-08-17 01:33
How is what you are doing different from this?
<img src="https://github.com/user-attachments/assets/a944d07e-7ea7-44a3-a53a-1de2510931d1" width="640" height="360">

**Comment by Trickiy** [comment] 2024-08-17 01:38
Hmm... The bottom blocks are level with the boarder, in a sec I will have a screenshot.

**Comment by Superbloxen** [comment] 2024-08-17 01:39
On second thought, this could be a version based issue, I was editing on a stable build of 1.3.6.x, I'll try 1.3.7-dev and notify of any differences...

**Comment by Superbloxen** [comment] 2024-08-17 01:45
>  this could be a version based issue
After testing it seems this issue persists on 1.3.7 too, possibly only affecting certain platforms (?)

**Comment by Trickiy** [comment] 2024-08-17 01:47
![image](https://github.com/user-attachments/assets/9a27a947-05ee-48be-a81f-ffa5d237874d)
The top is off by some pixels.

**Comment by Trickiy** [comment] 2024-08-17 02:02
I think the border logic might be doing incorrect checks on some but not all devices.

**Comment by Trickiy** [comment] 2024-08-17 02:11
ds-sloth it is possible that you are using a private build that isn't affected or already patched.

**Comment by ds-sloth** [comment] 2024-08-17 02:27
> After testing it seems this issue persists on 1.3.7 too, possibly only affecting certain platforms (?)

If you can get a screen recording on any of them that will be extremely helpful.

> The top is off by some pixels.

That is normal in all versions of SMBX, due to the fact that 600 is not a multiple of 32. You can adjust the section height if you want it to fit an even number of blocks.

> I am on the latest build.

I know that none of the recent commits have touched this logic so it doesn't make a difference in this case, but in general, it's helpful to share a build's commit hash instead of just the date / recency of the build.

> is it possible that you are using a private build

Oh, that is possible, in a bit of a weird way. My TheXTech codebase is 100% normal, but I'm using an updated version of the PGE-FileFormats library, and it's possible that this version might fix the bug here. Let me test with an older version.

**Comment by ds-sloth** [comment] 2024-08-17 02:36
Great, it looks like the root cause here is PGE-FL hardcoding certain values, so it should be easy to fix.

**Comment by Trickiy** [comment] 2024-08-17 02:39
Solution found lets gooo.

**Comment by ds-sloth** [comment] 2024-08-17 02:45
This one should also be fixed now, please confirm whenever you can!

**Comment by Trickiy** [comment] 2024-08-17 02:46
It's the weekend so I am going to imediently test the build when I see it's done.

**Comment by Trickiy** [comment] 2024-08-17 02:59
This issue is fixed but the world map curser misalignment issue is a little worse.
![image](https://github.com/user-attachments/assets/fec819d7-7a76-4820-a0ee-6035dfffbfb2)

**Comment by ds-sloth** [comment] 2024-08-17 03:02
Glad to hear this issue is fixed. I think you're right that the level cursor alignment is now incorrect but let's discuss that in the other issue.

**Closed** 2024-08-17 03:03 UTC
Labels: native bug, NEED A TEST
