### ISSUE TITLE
[Enhancement] Add ability to keep world- level- data in local GRAPHICS directory.

### ISSUE THREAD

**Issue by SkullGamer205** [TheXTech/TheXTech#640] opened 2023-11-11 14:01 UTC
## What i mean?

- I mean, create in the directory where the levels and the world are stored (.lvl / .lvlx / .wld / .wldx) the ability to create a **GRAPHICS** directory _(identical to graphics in the root of the game)_ for ergonomics, as well as for convenient data storage and retrieval.

_Why not._

**Comment by LoveBodhi** [comment] 2023-11-11 14:06
Part of #291 ?!

**Comment by M0REKZ** [comment] 2023-11-11 17:22
Is not it already possible by creating a folder with the same name as the level and put custom graphics there?

**Comment by ds-sloth** [comment] 2023-11-11 21:22
Good idea, duplicate of discussion in #15

**Closed** 2023-11-11 21:22 UTC
Labels: duplicate

**Comment by SkullGamer205** [comment] 2023-11-12 05:55
> Is not it already possible by creating a folder with the same name as the level and put custom graphics there?

It's possible, BUT, if you want to put GLOBAL graphics, You'll need to put this into "world" directory (where "world.wldx" located, which is not very convenient and takes up space in the directory, when it is more convenient to store shared / duplicate graphics somewhere in a folder and specify the path to it.

**Comment by Wohlstand** [comment] 2023-11-12 08:25
World map's directory works for world map only, not for episode-wide level resources.

**Comment by M0REKZ** [comment] 2023-11-12 15:27
> > Is not it already possible by creating a folder with the same name as the level and put custom graphics there?
> 
> It's possible, BUT, if you want to put GLOBAL graphics, You'll need to put this into "world" directory (where "world.wldx" located, which is not very convenient and takes up space in the directory, when it is more convenient to store shared / duplicate graphics somewhere in a folder and specify the path to it.

Oh, ok, then it's mainly to avoid the disorder that it could produce.
