### ISSUE TITLE
[Feature Request] 'Resource Packs' ala like minecraft

### ISSUE THREAD

**Issue by RunninPigeon** [TheXTech/TheXTech#502] opened 2023-03-21 03:28 UTC
For example, SFX, music, and player skins could be changed by opening the setting menu and opening 'Custom Packs' adding a whole new box of customizability.

**Comment by LoveBodhi** [comment] 2023-03-21 03:34
This makes me think about a mod, Mario Kart Wii Deluxe.
This also helps me to splitted version of Nostalgic Paradise.

**Comment by GoombarioFan** [comment] 2023-03-21 05:33
Sounds related to #261.

**Comment by ds-sloth** [comment] 2023-03-31 00:24
It's a very good idea but mostly a duplicate of #291, which we're internally developing. Thanks for the suggestion!

**Closed by ds-sloth** 2023-03-31 00:24 UTC
Labels: duplicate
